# Joining datasets
---

## 1. Analyze raw data

In [15]:
import pandas as pd

# read all of the csv previously generated and cleaned
cameras = pd.read_csv('./data/cameras.csv')
detections = pd.read_csv('./data/detections.csv')
sales = pd.read_csv('./data/sales.csv')
soldproducts = pd.read_csv('./data/soldproducts.csv')
stores = pd.read_csv('./data/stores.csv')
traffic = pd.read_csv("./data/traffic.csv")
zones = pd.read_csv('./data/zones.csv')

In [18]:
# display all the tables
print("cameras.csv")
display(cameras.head())

print("detections.csv")
display(detections.head())

print("sales.csv")
display(sales.head())

print("soldproducts.csv")
display(soldproducts.head())

print("stores.csv")
display(stores.head())

print("traffic.csv")
display(traffic.head())

print("zones.csv")
display(zones.head())

cameras.csv

,camera_id,zone_id,model,installation_date,condition,lims
0,ENTRCM_SRCL,ENTR_SRCL,Bullet,2025-10-25,Needs Maintenance,NaN
1,WMCM_SRCL,WM_SRCL,Fisheye,2024-04-12,Optimal,"{'x_min': 15, 'x_max': 28, 'y_min': 3, 'y_max'..."
2,MNCM_SRCL,MN_SRCL,Fisheye,2025-09-02,Good,"{'x_min': 28, 'x_max': 40, 'y_min': 0, 'y_max'..."
3,KDCM_SRCL,KD_SRCL,Fisheye,2025-08-30,Good,"{'x_min': 28, 'x_max': 40, 'y_min': 8, 'y_max'..."
4,COCM_SRCL,CO_SRCL,Turret,2024-09-16,Needs Maintenance,"{'x_min': 15, 'x_max': 22, 'y_min': 0, 'y_max'..."

detections.csv

,detection_id,tracking_id,camera_id,timestamp,class_object,coord_lims,confidence
0,b00616cc-0ac,TRK-798,ENTRCM_SRCL,2023-10-01T12:05:00,Staff,NaN,0.82
1,984e2a53-e35,TRK-192,ENTRCM_SRCL,2023-10-01T12:12:00,Staff,NaN,0.80
2,4357f5a9-c1f,TRK-143,ENTRCM_SRCL,2023-10-01T12:18:00,Staff,NaN,0.80
3,38219945-4ae,TRK-291,ENTRCM_SRCL,2023-10-01T12:27:00,Client,NaN,0.87
4,9b66f694-ffe,TRK-300,ENTRCM_SRCL,2023-10-01T12:35:00,Client,NaN,0.78

sales.csv

,ticket_id,store_id,timestamp,total_euros,product_amount,checkout_number
0,TKT-42126,SRAQ,2023-10-14T05:08:11,225.99,4,3
1,TKT-62135,SRBN,2023-10-24T02:16:32,222.44,4,1
2,TKT-50352,SRCL,2023-10-15T22:00:40,31.98,2,1
3,TKT-49679,SRCL,2023-10-10T19:06:47,102.48,3,1
4,TKT-28566,SRSL,2023-10-25T04:42:19,148.00,4,2

soldproducts.csv

  product_id  ticket_id  zone_id                  name   category   price
0   fc22841e  TKT-42126  KD_SRAQ      Kids Winter Coat  Outerwear   45.00
1   07716a68  TKT-42126  MN_SRAQ     Men Basic T-Shirt       Tops   15.99
2   616ec10e  TKT-42126  WM_SRAQ    Women Wool Sweater       Tops   45.00
3   756f5416  TKT-42126  WM_SRAQ  Women Leather Jacket  Outerwear  120.00
4   831aa91c  TKT-62135  MN_SRBN    Men Chino Trousers    Bottoms   39.99

stores.csv

  store_id     store_name      city   m2  max_capacity
0     SRCL     Sara Colon  Valencia  585           290
1     SRGV  Sara Gran Via  Valencia  585           290
2     SRAQ      Sara Aqua  Valencia  585           290
3     SRBN   Sara Bonaire  Valencia  585           290
4     SRSL     Sara Saler  Valencia  585           290

traffic.csv

,traffic_id,date_time,store_id,zone_id,visitor_count,average_time_in_store,peak_people,bounce_rate
0,120f325a-1a2,2023-10-01T10:00:00,SRCL,ENTR_SRCL,30,17.2,33,0.51
1,c8024239-cdc,2023-10-01T10:00:00,SRCL,WM_SRCL,51,7.8,60,0.34
2,cb167456-d5c,2023-10-01T10:00:00,SRCL,MN_SRCL,53,2.9,65,0.54
3,0233295f-969,2023-10-01T10:00:00,SRCL,KD_SRCL,49,3.0,60,0.60
4,d2414d1f-228,2023-10-01T10:00:00,SRCL,CO_SRCL,42,6.1,45,0.30

zones.csv

,zone_id,store_id,zone_name,zone_type,coord_lims
0,ENTR_SRCL,SRCL,Entrance,Entrance,NaN
1,WM_SRCL,SRCL,Women,Women clothes,"{'x_min': 15, 'x_max': 28, 'y_min': 3, 'y_max'..."
2,MN_SRCL,SRCL,Men,Men clothes,"{'x_min': 28, 'x_max': 40, 'y_min': 0, 'y_max'..."
3,KD_SRCL,SRCL,Kids,Kid clothes,"{'x_min': 28, 'x_max': 40, 'y_min': 8, 'y_max'..."
4,CO_SRCL,SRCL,Checkout,Checkout,"{'x_min': 15, 'x_max': 22, 'y_min': 0, 'y_max'..."

## 2. Join dataset

### 2.1 Infrastructure

In [46]:
# join cameras + zones `stores`
infrastructure = (
    cameras.merge(zones, on='zone_id', how='left')
           .merge(stores, on='store_id', how='left')  # left to include all cameras
           .rename(columns={
               'lims': 'camera_lims',
               'coord_lims': 'zone_lims',
               'condition': 'camera_condition'  # avoid confusions
           })
)

# reordering the columns
infrastructure = infrastructure[[
    'store_id', 'store_name', 'city',
    'zone_id', 'zone_name', 'zone_type', 'zone_lims',
    'camera_id', 'model','camera_condition','camera_lims', 
    'installation_date', 'm2', 'max_capacity'
]]

display(infrastructure.head())

,store_id,store_name,city,zone_id,zone_name,zone_type,zone_lims,camera_id,model,camera_condition,camera_lims,installation_date,m2,max_capacity
0,SRCL,Sara Colon,Valencia,ENTR_SRCL,Entrance,Entrance,NaN,ENTRCM_SRCL,Bullet,Needs Maintenance,NaN,2025-10-25,585,290
1,SRCL,Sara Colon,Valencia,WM_SRCL,Women,Women clothes,"{'x_min': 15, 'x_max': 28, 'y_min': 3, 'y_max'...",WMCM_SRCL,Fisheye,Optimal,"{'x_min': 15, 'x_max': 28, 'y_min': 3, 'y_max'...",2024-04-12,585,290
2,SRCL,Sara Colon,Valencia,MN_SRCL,Men,Men clothes,"{'x_min': 28, 'x_max': 40, 'y_min': 0, 'y_max'...",MNCM_SRCL,Fisheye,Good,"{'x_min': 28, 'x_max': 40, 'y_min': 0, 'y_max'...",2025-09-02,585,290
3,SRCL,Sara Colon,Valencia,KD_SRCL,Kids,Kid clothes,"{'x_min': 28, 'x_max': 40, 'y_min': 8, 'y_max'...",KDCM_SRCL,Fisheye,Good,"{'x_min': 28, 'x_max': 40, 'y_min': 8, 'y_max'...",2025-08-30,585,290
4,SRCL,Sara Colon,Valencia,CO_SRCL,Checkout,Checkout,"{'x_min': 15, 'x_max': 22, 'y_min': 0, 'y_max'...",COCM_SRCL,Turret,Needs Maintenance,"{'x_min': 15, 'x_max': 22, 'y_min': 0, 'y_max'...",2024-09-16,585,290

In [47]:
infrastructure.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   store_id           30 non-null     object
 1   store_name         30 non-null     object
 2   city               30 non-null     object
 3   zone_id            30 non-null     object
 4   zone_name          30 non-null     object
 5   zone_type          30 non-null     object
 6   zone_lims          25 non-null     object
 7   camera_id          30 non-null     object
 8   model              30 non-null     object
 9   camera_condition   30 non-null     object
 10  camera_lims        25 non-null     object
 11  installation_date  30 non-null     object
 12  m2                 30 non-null     int64
 13  max_capacity       30 non-null     int64
dtypes: int64(2), object(12)
memory usage: 3.4+ KB

This dataset provides a comprehensive technical audit of the retail network, transforming isolated hardware specs into a map that identifies exactly where the equipment is failing and confirms that the standardized store layouts are correctly supported by the right camera models across all Valencia locations.

### 2.2 Revenue

In [51]:
#join soldproducts + sales + stores
revenue = (
    soldproducts.merge(sales, on='ticket_id', how='inner')
                .merge(stores, on='store_id', how='left')
                .rename(columns={
                    'name': 'product_name',
                    'category': 'product_category',
                    'price': 'product_price' # avoid confusions
                })
)

# reorder
revenue = revenue[[
    'ticket_id', 'timestamp',
    'store_id','store_name', 'city',
    'product_id', 'product_name', 'product_category', 'product_price',
    'total_euros', 'product_amount',
    'checkout_number', 'zone_id',
    'm2', 'max_capacity'
]]

display(revenue.head())

,ticket_id,timestamp,store_id,store_name,city,product_id,product_name,product_category,product_price,total_euros,product_amount,checkout_number,zone_id,m2,max_capacity
0,TKT-42126,2023-10-14T05:08:11,SRAQ,Sara Aqua,Valencia,fc22841e,Kids Winter Coat,Outerwear,45.00,225.99,4,3,KD_SRAQ,585,290
1,TKT-42126,2023-10-14T05:08:11,SRAQ,Sara Aqua,Valencia,07716a68,Men Basic T-Shirt,Tops,15.99,225.99,4,3,MN_SRAQ,585,290
2,TKT-42126,2023-10-14T05:08:11,SRAQ,Sara Aqua,Valencia,616ec10e,Women Wool Sweater,Tops,45.00,225.99,4,3,WM_SRAQ,585,290
3,TKT-42126,2023-10-14T05:08:11,SRAQ,Sara Aqua,Valencia,756f5416,Women Leather Jacket,Outerwear,120.00,225.99,4,3,WM_SRAQ,585,290
4,TKT-62135,2023-10-24T02:16:32,SRBN,Sara Bonaire,Valencia,831aa91c,Men Chino Trousers,Bottoms,39.99,222.44,4,1,MN_SRBN,585,290

In [52]:
revenue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticket_id         598 non-null    object
 1   timestamp         598 non-null    object
 2   store_id          598 non-null    object
 3   store_name        598 non-null    object
 4   city              598 non-null    object
 5   product_id        598 non-null    object
 6   product_name      598 non-null    object
 7   product_category  598 non-null    object
 8   product_price     598 non-null    float64
 9   total_euros       598 non-null    float64
 10  product_amount    598 non-null    int64
 11  checkout_number   598 non-null    int64
 12  zone_id           598 non-null    object
 13  m2                598 non-null    int64
 14  max_capacity      598 non-null    int64
dtypes: float64(2), int64(4), object(9)
memory usage: 70.2+ KB

This is the backbone of retail analytics; it connects what was bought and where, allowing the stores to move beyond simple revenue totals to granular item-level performance. This dataset provides a better view of sales performance that identifies which product categories are top-sellers in specific cities and calculates the average transaction value relative to the physical capacity and checkout efficiency of each store location.

### 2.3 Validation

In [64]:
# convert timestamps
detections['timestamp'] = pd.to_datetime(detections['timestamp'])
traffic['date_time'] = pd.to_datetime(traffic['date_time'])

# Fix: Lowercase 'h' for rounding
detections['hour_key'] = detections['timestamp'].dt.floor('h')
traffic['hour_key'] = traffic['date_time'].dt.floor('h')

# We join detections with cameras first to inherit the 'zone_id'
detections_with_zones = pd.merge(
    detections, 
    cameras[['camera_id', 'zone_id']], 
    on='camera_id', 
    how='left'
)

# now we can join with traffic because we have 'zone_id'
validation = pd.merge(
    detections_with_zones, 
    traffic, 
    on=['zone_id', 'hour_key'], 
    how='inner'
)

# Clean and reorder the validation dataset
validation = (
    validation.drop(columns=['store_id_y'])
              .rename(columns={'store_id_x': 'store_id'})
)

validation = validation[[
    'detection_id','tracking_id',
    'hour_key', 'timestamp', 'date_time', 'traffic_id',
    'store_id', 'zone_id', 'camera_id',
    'class_object',
    'visitor_count', 'peak_people',
    'confidence', 'coord_lims',
    'average_time_in_store', 'bounce_rate'
]]

display(validation.head())

,detection_id,tracking_id,hour_key,timestamp,date_time,traffic_id,store_id,zone_id,camera_id,class_object,visitor_count,peak_people,confidence,coord_lims,average_time_in_store,bounce_rate
0,b00616cc-0ac,TRK-798,2023-10-01 12:00:00,2023-10-01 12:05:00,2023-10-01 12:00:00,bf98d9f7-2ff,SRCL,ENTR_SRCL,ENTRCM_SRCL,Staff,31,39,0.82,NaN,8.6,0.17
1,984e2a53-e35,TRK-192,2023-10-01 12:00:00,2023-10-01 12:12:00,2023-10-01 12:00:00,bf98d9f7-2ff,SRCL,ENTR_SRCL,ENTRCM_SRCL,Staff,31,39,0.80,NaN,8.6,0.17
2,4357f5a9-c1f,TRK-143,2023-10-01 12:00:00,2023-10-01 12:18:00,2023-10-01 12:00:00,bf98d9f7-2ff,SRCL,ENTR_SRCL,ENTRCM_SRCL,Staff,31,39,0.80,NaN,8.6,0.17
3,38219945-4ae,TRK-291,2023-10-01 12:00:00,2023-10-01 12:27:00,2023-10-01 12:00:00,bf98d9f7-2ff,SRCL,ENTR_SRCL,ENTRCM_SRCL,Client,31,39,0.87,NaN,8.6,0.17
4,9b66f694-ffe,TRK-300,2023-10-01 12:00:00,2023-10-01 12:35:00,2023-10-01 12:00:00,bf98d9f7-2ff,SRCL,ENTR_SRCL,ENTRCM_SRCL,Client,31,39,0.78,NaN,8.6,0.17

In [65]:
validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   detection_id           720 non-null    object
 1   tracking_id            720 non-null    object
 2   hour_key               720 non-null    datetime64[ns]
 3   timestamp              720 non-null    datetime64[ns]
 4   date_time              720 non-null    datetime64[ns]
 5   traffic_id             720 non-null    object
 6   store_id               720 non-null    object
 7   zone_id                720 non-null    object
 8   camera_id              720 non-null    object
 9   class_object           720 non-null    object
 10  visitor_count          720 non-null    int64
 11  peak_people            720 non-null    int64
 12  confidence             720 non-null    float64
 13  coord_lims             600 non-null    object
 14  average_time_in_store  720 non-null    float64
 15  bounce_rate            720 non-null    float64
dtypes: datetime64[ns](3), float64(3), int64(2), object(8)
memory usage: 90.1+ KB

this join is critical for data validation because it cross-references the detections against traffic within the same hour and area.This is useful to validate sensor precision and identify discrepancies between computer vision and hardware-based visitor counts in specific zones.

## 3. Save new datasets

In [66]:
infrastructure.to_csv('data/joined_datasets/infrastructure.csv', index=False)
revenue.to_csv('data/joined_datasets/revenue.csv', index=False)
validation.to_csv('data/joined_datasets/validation.csv', index=False)